# Generated by Django 4.1.7 on 2023-03-21 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('move_text', models.CharField(max_length=10)),
                ('explanation', models.TextField()),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpeningAnalysis.chessopening')),
            ],
        ),
    ]
