# Generated by Django 4.1.7 on 2023-03-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpeningAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessopening',
            name='moves',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chessopening',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='OpeningMove',
        ),
    ]
