# Generated by Django 4.1.7 on 2023-03-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpeningAnalysis', '0002_chessopening_moves_alter_chessopening_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessopening',
            name='variation',
            field=models.TextField(default='없음'),
        ),
    ]
